name: Actualizar Enlace M3U8 de Telemundo

on:
  # Te permite ejecutar el script manualmente haciendo un clic desde la web de GitHub
  workflow_dispatch:

jobs:
  extractor:
    runs-on: ubuntu-latest

    steps:
    # 1. Copia tus archivos en el servidor virtual de GitHub
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    # 2. Instala Node.js en el servidor de GitHub
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    // 3. Instala Puppeteer y sus dependencias de Chrome para Linux de forma limpia
    - name: Instalar dependencias del proyecto
      run: |
        npm init -y
        npm install puppeteer
        sudo apt-get update
        sudo apt-get install -y libgbm-dev wget gnupg
        
    # 4. Ejecuta tu script oculto de fondo
    - name: Correr Extractor Automático
      run: node app.js

    # 5. Guarda el archivo lista.m3u8 generado en tu repositorio público/privado
    - name: Guardar cambios y subir enlace actualizado
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add lista.m3u8
        git commit -m "Actualización automática del enlace M3U8" || exit 0
        git push
