name: Actualizar Enlace M3U8 de Telemundo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extractor:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias de Node y Navegador
      run: npm install

    - name: Correr Extractor Automatico
      run: node app.js

    - name: Guardar cambios y subir enlace actualizado
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add lista.m3u8
        git commit -m "Actualizacion automatica del enlace M3U8" || exit 0
        git push
