name: Ejecutar script M3U8 cada hora

on:
  schedule:
    # Se ejecuta automáticamente en el minuto 0 de cada hora
    - cron: '0 * * * *'
  # Mantiene el botón manual en la pestaña Actions por si quieres forzar la actualización
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar script de actualización
      run: node app.js

    - name: Guardar cambios en GitHub
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lista.m3u8
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizacion automatica del enlace M3U8" && git push)
